// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApplication15.Entities
{
    public partial class Customers
    {
        public Guid CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerUsername { get; set; }
        public string Password { get; set; }
    }
}