// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApplication15.Entities
{
    public partial class TestDatas
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public int Timestamp { get; set; }
        public int Uid { get; set; }
        public string SendgridEventId { get; set; }
        public string SmtpId { get; set; }
        public string SgMessageId { get; set; }
        public string SendgridEvent { get; set; }
        public int MarketingCampaignId { get; set; }
        public string MarketingCampaignName { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Url { get; set; }
        public string Useragent { get; set; }
        public string Ip { get; set; }
        public string Response { get; set; }
        public string CreationDate { get; set; }
        public Guid CustomerId { get; set; }
    }
}